# Chatbot với keras

In [1]:
import os
urls = os.listdir(os.path.expanduser("data_chatbot"))
urls.remove(".DS_Store")
answers = []
questions = []
for url in urls:
    path = 'data_chatbot/'+url
    with open(path,encoding= 'utf-8-sig') as f:
        f_bb = f.read().splitlines()
   
    for i in range(len(f_bb)):
        a = str(f_bb[i]).split(' __eou__')
        questions.append((a[0].lower()))
        answers.append((a[1].strip().lower()))
#print(questions[1020])
print(questions[0:3])
print(answers[0:3])


['bạn thích hãng phim nào nhất ?', 'thể loại phim bạn thích là gì ?', 'bạn có thần tượng ca sĩ nào không ?']
['mình thích hãng phim marvel nhất', 'mình thích thể loại phim hành động, viễn tưởng', 'mình rất thích ca sĩ noo phước thịnh']


# Tách từ dùng Underthesea

In [3]:
from underthesea import word_tokenize
sentences = [word_tokenize(sent) for sent in questions]
print(sentences)


[['bạn', 'thích', 'hãng', 'phim', 'nào', 'nhất', '?'], ['thể loại', 'phim', 'bạn', 'thích', 'là', 'gì', '?'], ['bạn', 'có', 'thần tượng', 'ca sĩ', 'nào', 'không', '?'], ['bạn', 'có', 'muốn', 'thử', 'vận', 'may', 'vào', 'việc', 'chơi', 'đề', '?'], ['tết', 'này', 'bạn', 'có', 'muốn', 'đi', 'xem', 'phim', 'không', '?'], ['cuối', 'tuần', 'này', 'bạn', 'có', 'rãnh', 'hay', 'không', '?'], ['bạn', 'có', 'muốn', 'đi', 'xem', 'phim', 'vào', 'cuối', 'tuần', 'này', 'hay', 'không', '?'], ['mai', 'bạn', 'có', 'muốn', 'đi', 'đá', 'banh', 'chung', 'với', 'tụi mình', 'không', '?'], ['bạn', 'có', 'dự định', 'đi', 'chơi', 'đâu', 'vào', 'cuối', 'tuần', 'không', '?'], ['bạn', 'cho', 'mình', 'hỏi', 'bạn', 'thích', 'xem', 'phim', 'thể loại', 'gì', '?'], ['bạn', 'cho', 'mình', 'hỏi', 'bạn', 'có', 'hay', 'đi', 'chơi', 'ở', 'đâu', 'không', '?'], ['bạn', 'cho', 'mình', 'hỏi', 'bạn', 'thích', 'xem', 'phim', 'gì', 'nhất', '?'], ['bạn', 'cho', 'mình', 'hỏi', 'bạn', 'thường', 'đi', 'xem', 'phim', 'chung', 'với', 'a

# Fit_on_texts câu

In [4]:
from keras.preprocessing.text import Tokenizer 
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
print(tokenizer.word_index)

{'?': 1, 'bạn': 2, 'không': 3, 'có': 4, 'gì': 5, 'mình': 6, 'ở': 7, 'đi': 8, 'vậy': 9, ',': 10, 'nào': 11, 'đâu': 12, 'cho': 13, 'là': 14, 'của': 15, 'cậu': 16, 'làm': 17, 'bao nhiêu': 18, 'thích': 19, 'hay': 20, 'hỏi': 21, 'đang': 22, 'với': 23, 'học': 24, 'chơi': 25, 'này': 26, 'quê': 27, 'trường': 28, 'chưa': 29, 'thế nào': 30, 'về': 31, 'người': 32, 'mày': 33, 'nhà': 34, 'ăn': 35, 'muốn': 36, 'như': 37, 'được': 38, 'em': 39, 'phim': 40, 'rồi': 41, 'biết': 42, 'ạ': 43, 'người yêu': 44, 'thế': 45, 'tên': 46, 'thì': 47, 'ai': 48, 'tết': 49, 'xem': 50, 'khi': 51, 'thường': 52, 'mấy': 53, 'mua': 54, 'năm': 55, 'trong': 56, 'đó': 57, 'sao': 58, 'nhất': 59, 'còn': 60, 'để': 61, '.': 62, 'tuổi': 63, 'tao': 64, 'gia đình': 65, 'đã': 66, 'có thể': 67, 'những': 68, 'một': 69, 'ơi': 70, 'anh': 71, 'công việc': 72, 'vào': 73, 'ngành': 74, 'mà': 75, 'bạn bè': 76, 'nghề': 77, 'thấy': 78, 'sống': 79, 'du lịch': 80, 'rảnh': 81, 'nhiều': 82, 'sinh': 83, 'yêu': 84, 'nhỉ': 85, 'ông': 86, 'ra': 87, 'tạ

# Mode Count

In [5]:
X_count = tokenizer.texts_to_matrix(sentences,mode='count')
print(X_count.shape)
X_count

(5855, 2534)


array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

# Mode Tfidf

In [6]:
X_tfidf = tokenizer.texts_to_matrix(sentences,mode='tfidf')
print(X_tfidf.shape)
X_tfidf

(5855, 2534)


array([[0.        , 0.73220476, 0.95155618, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.73220476, 0.95155618, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.73220476, 0.95155618, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.73220476, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.73220476, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.73220476, 0.95155618, ..., 0.        , 0.        ,
        0.        ]])

# Chuyển đổi câu về ma trận sử dụng 2 loại: count và tfidf

In [7]:
question_count =['thể loại phim bạn thích là gì ?'] 
sentence_count = [word_tokenize(sent) for sent in question_count]
count_vector = tokenizer.texts_to_matrix(sentence_count, mode = 'count')
tfidf_vector = tokenizer.texts_to_matrix(sentence_count, mode = 'tfidf')
print(sentence_count)


[['thể loại', 'phim', 'bạn', 'thích', 'là', 'gì', '?']]


In [8]:
print(count_vector.shape)
print('Mode count: ',count_vector)

(1, 2534)
Mode count:  [[0. 1. 1. ... 0. 0. 0.]]


In [9]:
print(tfidf_vector.shape)
print('Mode Tfidf: ',tfidf_vector)

(1, 2534)
Mode Tfidf:  [[0.         0.73220476 0.95155618 ... 0.         0.         0.        ]]


In [10]:
from sklearn.metrics.pairwise import cosine_similarity 
def chat_count(x):
    x = [word_tokenize(i) for i in x]
    x_vector = tokenizer.texts_to_matrix(x,mode='count')
    response = '' 
    most_sim = 0  
    for i in range(len(questions)):  
        if most_sim < cosine_similarity(X_count[i].reshape(1,-1), x_vector[0].reshape(1,-1)):  
            most_sim = cosine_similarity(X_count[i].reshape(1,-1), x_vector[0].reshape(1,-1))  
            answer_index = i                    
            response = answers[answer_index] 
    return response

In [11]:
def chat_tfidf(x):
    x = [word_tokenize(i) for i in x]
    x_vector = tokenizer.texts_to_matrix(x,mode='tfidf')
    response = '' 
    most_sim = 0  
    for i in range(len(questions)):  
        if most_sim < cosine_similarity(X_tfidf[i].reshape(1,-1), x_vector[0].reshape(1,-1)):  
            most_sim = cosine_similarity(X_tfidf[i].reshape(1,-1), x_vector[0].reshape(1,-1))  
            answer_index = i                    
            response = answers[answer_index] 
    return response

In [12]:
print('Bot Count: ',chat_count(['chào']))

Bot Count:  chào bạn, bạn muốn tôi giúp gì?


In [13]:
print('Bot Tfidf: ',chat_tfidf(['chào']))

Bot Tfidf:  chào bạn, mình tên là hùng


In [14]:
print('Bot Count: ',chat_count(['bot ơi']))

Bot Count:  mình nghe nè bạn ơi


In [15]:
print('Bot Tfidf: ',chat_tfidf(['bot ơi']))

Bot Tfidf:  tui thích cả hai.


In [16]:
print('Bot Count: ',chat_count(['nhà ở đâu ?']))

Bot Count:  nhà mình ở bên mỹ tho


In [17]:
print('Bot Tfidf: ',chat_tfidf(['nhà ở đâu ?']))

Bot Tfidf:  nhà mình ở bên mỹ tho


In [18]:
print('Bot Count: ',chat_count(['thích đi chơi không ?']))

Bot Count:  ok đi chơi đi buồn quá nè


In [19]:
print('Bot Tfidf: ',chat_tfidf(['thích đi chơi không ?']))

Bot Tfidf:  ok đi chơi đi buồn quá nè


In [20]:
print('Bot Count: ',chat_count(['thể loại phim thích coi là gì ?']))

Bot Count:  mình thích thể loại phim hành động, viễn tưởng


In [21]:
print('Bot Tfidf: ',chat_tfidf(['thể loại phim thích coi là gì ?']))

Bot Tfidf:  mình thích coi phim 18+


In [22]:
print('Bot Count: ',chat_count(['ai tạo ra bot ?']))

Bot Count:  python tạo ra tao


In [23]:
print('Bot Tfidf: ',chat_tfidf(['ai tạo ra bot ?']))

Bot Tfidf:  python tạo ra tao


In [24]:
# import sys
# x = input('You: \n')
# while x!='QUIT':
#     print('Bot: ')
#     chat([x])
#     x = input('\nYou: \n')
# if x=='QUIT':
#     print('\nBot: TẠM BIỆT')
#     exit
    

# Chatbot Sklearn

In [25]:
from pyvi import ViTokenizer
ques = []
for i in (questions):
    ques.append(ViTokenizer.tokenize(i))
print(ques)

['bạn thích hãng phim nào nhất ?', 'thể_loại phim bạn thích là gì ?', 'bạn có thần_tượng ca_sĩ nào không ?', 'bạn có muốn thử vận may vào việc chơi đề ?', 'tết này bạn có muốn đi xem phim không ?', 'cuối tuần này bạn có rãnh hay không ?', 'bạn có muốn đi xem phim vào cuối tuần này hay không ?', 'mai bạn có muốn đi đá banh chung với tụi mình không ?', 'bạn có dự_định đi chơi đâu vào cuối tuần không ?', 'bạn cho mình hỏi bạn thích xem phim thể_loại gì ?', 'bạn cho mình hỏi bạn có hay đi chơi ở đâu không ?', 'bạn cho mình hỏi bạn thích xem phim gì nhất ?', 'bạn cho mình hỏi bạn thường đi xem phim chung với ai ?', 'bạn cho mình hỏi bạn có thích xem phim kinh_dị không ?', 'bạn cho mình hỏi bạn có thích ăn gì trong khi xem phim không ?', 'phim hồi nãy hay không ?', 'phim này gay_cấn nhỉ ?', 'hôm_nay đi xem phim chứ ?', 'cậu muốn coi phim gì ?', 'hôm_nay mình đi xem phim tại cgv nhé ?', 'mình đi xem phim ở đâu ?', 'phim hồi nãy hay không ?', 'phim này gay_cấn nhỉ ?', 'hôm_nay đi xem phim chứ 

# Mode Tfidf

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer  
vectorizer_tfidf= TfidfVectorizer()  
X_tfidf = vectorizer_tfidf.fit(ques)   
array_tfidf = X_tfidf.transform(ques).toarray()
array_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Mode Hashing

In [27]:
from sklearn.feature_extraction.text import HashingVectorizer  
vectorizer_hash= HashingVectorizer(n_features=16)  
X_hash = vectorizer_hash.fit(ques)   
array_hash = X_hash.transform(ques).toarray()
array_hash

array([[ 0.        ,  0.        ,  0.        , ...,  0.5       ,
         0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.40824829,
         0.        ,  0.40824829],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.28867513,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ..., -0.31622777,
         0.31622777,  0.        ],
       [-0.33333333,  0.        ,  0.        , ...,  0.        ,
         0.33333333,  0.33333333]])

In [28]:
import numpy as np  
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
test_question ='hôm nay đi xem phim chứ?'
print(ViTokenizer.tokenize((test_question)))


hôm_nay đi xem phim chứ ?


In [30]:
vector_count = X_tfidf.transform([test_question]).toarray()#.reshape(1,-1) 
print('Count: ',vector_count)

Count:  [[0. 0. 0. ... 0. 0. 0.]]


In [31]:
vector_hash = X_hash.transform([test_question]).toarray()#.reshape(1,-1) 
print('Hash: ',vector_hash)

Hash:  [[ 0.         -0.35355339  0.          0.35355339  0.          0.
   0.          0.          0.35355339  0.          0.          0.
   0.          0.70710678  0.          0.35355339]]


In [32]:
def chat_tfidf(x):
    x = ViTokenizer.tokenize(x)
    test_vector = X_tfidf.transform([x]).toarray()
    response = '' 
    most_sim = 0  
    for i in range(len(questions)):  
        if most_sim < cosine_similarity(array_tfidf[i].reshape(1,-1), test_vector[0].reshape(1,-1)):  
            most_sim = cosine_similarity(array_tfidf[i].reshape(1,-1), test_vector[0].reshape(1,-1))  
            answer_index = i                    
            response = answers[answer_index] 
    return response

In [33]:
def chat_hashing(x):
    x = ViTokenizer.tokenize(x)
    test_vector = X_hash.transform([x]).toarray()
    response = '' 
    most_sim = 0  
    for i in range(len(questions)):  
        if most_sim < cosine_similarity(array_hash[i].reshape(1,-1), test_vector[0].reshape(1,-1)):  
            most_sim = cosine_similarity(array_hash[i].reshape(1,-1), test_vector[0].reshape(1,-1))  
            answer_index = i                    
            response = answers[answer_index] 
    return response

# Sklearn predict

In [34]:
print('Bot Tfidf: ',chat_tfidf('bạn học ở đâu ?'))

Bot Tfidf:  mình học trường tôn đức thắng


In [35]:
print('Bot Hashing: ',chat_hashing('bạn học ở đâu ?'))

Bot Hashing:  mình học trường tôn đức thắng


In [36]:
print('Bot Tfidf: ',chat_tfidf('crush tên gì ?'))

Bot Tfidf:  hải


In [37]:
print('Bot Hashing: ',chat_hashing('crush tên gì ?'))

Bot Hashing:  khoa tcnh


In [38]:
print('Bot Tfidf: ',chat_tfidf('thời tiết hôm nay thế nào ?'))

Bot Tfidf:  nắng vàng tươi ạ.


In [39]:
print('Bot Hashing: ',chat_hashing('thời tiết hôm nay thế nào ?'))

Bot Hashing:  tui không phải máy dự báo thời tiết, nên không thể trả lời bạn được


In [40]:
print('Bot Tfidf: ',chat_tfidf('mày có cúp học không ?'))

Bot Tfidf:  cũng có. tao thấy thằng lý lý anh hay rủ cúp học nên bị lôi kéo


In [41]:
print('Bot Hashing: ',chat_hashing('mày có cúp học không ?'))

Bot Hashing:  không quá xa trường tdtu


In [ ]:
# import sys
# def chat_sklearn():
#     x = input('You: \n')
#     while x!='QUIT':
#         print('Bot: ')
#         chat([x])
#         x = input('\nYou: \n')
#     if x=='QUIT':
#         print('\nBot: TẠM BIỆT')
#         exit
# chat_sklearn()